import {escapeHtml as esc,states,taskNames,clock,minutes} from './format.mjs';
import {analyzeRun} from './replay-model.mjs';

export const metric=(label,value,unit='',sub='',tone='',icon='')=>`<div class="metric ${tone}"><div class="metric-label">${esc(label)}<span class="metric-icon" aria-hidden="true">${icon}</span></div><strong>${esc(value)}</strong><small>${esc(unit)}</small>${sub?`<span class="metric-sub">${esc(sub)}</span>`:''}</div>`;
const utilBars=data=>data.agfs.map(a=>`<div class="util-row"><span>${esc(a.id)}</span><div class="util-track"><i style="width:${a.utilizationPct}%"></i></div><b>${a.utilizationPct.toFixed(1)}%</b></div>`).join('');
const kindTable=data=>`<div class="table-scroll"><table><thead><tr><th>搬送区分</th><th>要求</th><th>完了</th><th>未完了</th></tr></thead><tbody>${data.byKind.map(k=>`<tr><td><span class="mono">${k.kind}</span> ${taskNames[k.kind]}</td><td>${k.requested}</td><td>${k.completed}</td><td>${k.pending}</td></tr>`).join('')}</tbody></table></div>`;
export function renderAnalysis(run,data=analyzeRun(run)) {
  return `<div class="analysis-metrics">${metric('搬送要求数',data.requested,'件','01〜05の発行済み要求','accent','↗')}${metric('完了タスク',data.completed,'件','実行期間内の完了','success','✓')}${metric('保留タスク',data.held,'件',`未完了 ${data.pending}件 / 02発行前保留 ${data.preRequestHeld}PL`,'warning','◷')}${metric('AGF平均稼働率',data.utilizationPct.toFixed(1),'%','空走・荷受け＋積載・荷下ろし','accent','▥')}
    ${metric('待機時間',minutes(data.idleMs),'分','4台合計・未割当の待機')}${metric('充電時間',minutes(data.chargeMs),'分','4台合計・充電中')}${metric('充電待ち時間',minutes(data.chargeWaitMs),'分','4台合計・2口の空き待ち')}${metric('要求から割当まで',minutes(data.requestWaitMs),'分','未割当は実行終了までを集計')}</div>
    <section class="panel"><div class="panel-heading"><div><h2>AGF タイムライン</h2><span class="muted">保存済みスナップショットの状態継続時間 · ${run.scenario.durationMin}分間</span></div><span class="badge">全期間</span></div><div class="timeline-axis">${[0,.25,.5,.75,1].map(n=>`<span>${clock(data.durationMs*n)}</span>`).join('')}</div>
    ${data.agfs.map(a=>`<div class="timeline-row"><strong>${esc(a.id)}</strong><div class="timeline-track" role="img" aria-label="${a.id} 稼働率${a.utilizationPct.toFixed(1)}%、状態別時間は下表参照">${a.timeline.map(s=>`<span class="timeline-segment timeline-${esc(s.status)}" style="width:${(s.endMs-s.startMs)*100/data.durationMs}%" title="${esc((states[s.status]??s.status)+' '+clock(s.startMs)+'–'+clock(s.endMs)+(s.taskId?' '+s.taskId:''))}"></span>`).join('')}</div></div>`).join('')}
    <div class="timeline-legend">${['idle','moving_empty','moving_loaded','wait_drop','moving_to_charge','charging','waiting_charge'].map(s=>`<span><i class="legend-dot timeline-${s}"></i>${states[s]}</span>`).join('')}</div></section>
    <div class="analysis-grid"><section class="panel"><div class="panel-heading"><h2>搬送別実績</h2><span class="muted">件</span></div>${kindTable(data)}</section><section class="panel"><div class="panel-heading"><h2>AGF別 稼働率</h2><span class="muted">全期間に対する作業時間</span></div>${utilBars(data)}<p class="method-note">充電・充電移動・荷下ろし待ちは稼働率に含めません。走行と荷役は現モデルのイベント単位で集計します。</p></section></div>
    <section class="panel"><div class="panel-heading"><h2>AGF別 時間内訳</h2><span class="muted">単位：分 / 各行の合計は実行時間</span></div><div class="table-scroll"><table><thead><tr><th>AGF</th>${['idle','moving_empty','moving_loaded','wait_drop','moving_to_charge','charging','waiting_charge'].map(s=>`<th>${states[s]}</th>`).join('')}</tr></thead><tbody>${data.agfs.map(a=>`<tr><td>${a.id}</td>${['idle','moving_empty','moving_loaded','wait_drop','moving_to_charge','charging','waiting_charge'].map(s=>`<td>${minutes(a.durations[s]??0)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>
    <p class="method-note section">集計根拠：実行開始から終了まで、同時刻イベントは順序適用後の状態を使用。末尾イベント後の継続時間も含みます。未発行の02保留はタスク数とは別に集計します。実走行距離・実設備の稼働率・交通ボトルネックは未検証です。</p>`;
}
export function renderComparison(runs) {
  const data=runs.map(analyzeRun);
  const scenario=runs[0].scenario;
  return `<details class="panel comparison-conditions"><summary>比較に使った共通条件 · ${scenario.durationMin}分 / ${runs[0].events.filter(e=>e.type==='PALLET_EXITED').length}PL搬出</summary><p class="method-note section">系列1〜8の間隔（分）：${scenario.lineIntervalsMin.map(n=>n===0?'停止':n).join(' / ')}<br>初回ずらし（分）：${scenario.lineStartOffsetsMin.join(' / ')}<br>初期残量：${scenario.agfs.map(a=>a.id+' '+a.batteryPct+'%').join(' / ')}<br>空走 ${scenario.times.emptyMin}分・積載 ${scenario.times.loadedMin}分・荷受け ${scenario.times.pickupMin}分・荷下ろし ${scenario.times.dropoffMin}分<br>手動予約 ${scenario.manualRequests.length}件 / マガジン使用 ${scenario.magazineUses.length}件 / 整列機準備 ${scenario.alignerReadyEvents.length}件<br>目的地エリアに実行可能AGFなし：${scenario.fallback==='any'?'他エリアから選定（仮定）':'待機'}</p></details><div class="comparison-grid">${runs.map((run,i)=>`<section class="panel strategy-panel"><p class="eyebrow">STRATEGY ${String(i+1).padStart(2,'0')}</p><h2>${i===0?'エリア優先あり':'エリア優先なし'}</h2><p class="muted">${i===0?'目的地エリアの実行可能AGFを優先':'全エリアの実行可能AGFから選定'}</p><div class="strategy-kpis">${metric('完了タスク',data[i].completed,'件','','success')}${metric('入庫完了',run.metrics.stored,'PL')}${metric('平均稼働率',data[i].utilizationPct.toFixed(1),'%','','accent')}${metric('保留タスク',data[i].held,'件','','warning')}</div>${utilBars(data[i])}${kindTable(data[i])}</section>`).join('')}</div>
    <section class="panel"><div class="panel-heading"><h2>同一条件の比較</h2><span class="badge sample">${runs[0].scenario.durationMin}分 / 合成入力</span></div><div class="table-scroll"><table><thead><tr><th>指標</th><th>エリア優先あり</th><th>エリア優先なし</th><th>差（あり − なし）</th></tr></thead><tbody>${[
      ['要求数（件）',...data.map(d=>d.requested)],['完了数（件）',...data.map(d=>d.completed)],['未完了数（件）',...data.map(d=>d.pending)],
      ['02発行前保留（PL）',...data.map(d=>d.preRequestHeld)],['要求待ち（分）',...data.map(d=>Number(minutes(d.requestWaitMs)))],
      ['待機時間（分）',...data.map(d=>Number(minutes(d.idleMs)))],['充電時間（分）',...data.map(d=>Number(minutes(d.chargeMs)))],
      ['充電待ち（分）',...data.map(d=>Number(minutes(d.chargeWaitMs)))]
    ].map(([label,a,b])=>`<tr><td>${label}</td><td>${a}</td><td>${b}</td><td>${Number((a-b).toFixed(1))>0?'+':''}${Number((a-b).toFixed(1))}</td></tr>`).join('')}</tbody></table></div></section><p class="method-note section">比較には実行時点の設定と手動入力を複製して使用。搬出時刻・系列・パレットIDは共通です。設定を変更した場合は比較実行で更新してください。差がない条件では同じ値を表示します。</p>`;
}
